vpn_locations = {
    "al": ["tia"],
    "au": ["adl", "bne", "mel", "per", "syd"],
    "at": ["vie"],
    "be": ["bru"],
    "br": ["sao"],
    "bg": ["sof"],
    "ca": ["yyc", "mtr", "tor", "van"],
    "cl": ["scl"],
    "co": ["bog"],
    "hr": ["zag"],
    "cy": ["nic"],
    "cz": ["prg"],
    "dk": ["cph"],
    "ee": ["tll"],
    "fi": ["hel"],
    "fr": ["bod", "mrs", "par"],
    "de": ["ber", "dus", "fra"],
    "gr": ["ath"],
    "hk": ["hkg"],
    "hu": ["bud"],
    "id": ["jpu"],
    "ie": ["dub"],
    "il": ["tlv"],
    "it": ["mil", "pmo"],
    "jp": ["osa", "tyo"],
    "mx": ["qro"],
    "nl": ["ams"],
    "nz": ["akl"],
    "ng": ["los"],
    "no": ["osl", "svg"],
    "pe": ["lim"],
    "ph": ["mnl"],
    "pl": ["waw"],
    "pt": ["lis"],
    "ro": ["buh"],
    "rs": ["beg"],
    "sg": ["sin"],
    "sk": ["bts"],
    "si": ["lju"],
    "za": ["jnb"],
    "es": ["bcn", "mad", "vlc"],
    "se": ["got", "mma", "sto"],
        "ch": ["zrh"],
    "th": ["bkk"],
    "tr": ["ist"],
    "gb": ["glw", "lon", "mnc"],
    "ua": ["iev"],
    "us": [
        "qas", "atl", "bos", "chi", "dal", "den", "det", "hou", "lax",
        "txc", "mia", "nyc", "phx", "rag", "slc", "sjc", "sea", "uyk"
    ]
}
